// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsw-1vb5qxatn3RUELtY_Fv4VUWvwsqqQ',
    appId: '1:1094596354591:web:677910a18818e953036b2a',
    messagingSenderId: '1094596354591',
    projectId: 'check-93786',
    authDomain: 'check-93786.firebaseapp.com',
    storageBucket: 'check-93786.firebasestorage.app',
    measurementId: 'G-SQ98N04VX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCBfpuuftQGIO1sF3NxHNeuwfhccCrsI',
    appId: '1:1094596354591:android:61df6e496bd39ced036b2a',
    messagingSenderId: '1094596354591',
    projectId: 'check-93786',
    storageBucket: 'check-93786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJtwZHxYn3g5wMArygAi5LJ51qmwjctM',
    appId: '1:1094596354591:ios:03e63c596bfe0f18036b2a',
    messagingSenderId: '1094596354591',
    projectId: 'check-93786',
    storageBucket: 'check-93786.firebasestorage.app',
    iosBundleId: 'com.example.check',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJtwZHxYn3g5wMArygAi5LJ51qmwjctM',
    appId: '1:1094596354591:ios:03e63c596bfe0f18036b2a',
    messagingSenderId: '1094596354591',
    projectId: 'check-93786',
    storageBucket: 'check-93786.firebasestorage.app',
    iosBundleId: 'com.example.check',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsw-1vb5qxatn3RUELtY_Fv4VUWvwsqqQ',
    appId: '1:1094596354591:web:daa5c3c908dffef8036b2a',
    messagingSenderId: '1094596354591',
    projectId: 'check-93786',
    authDomain: 'check-93786.firebaseapp.com',
    storageBucket: 'check-93786.firebasestorage.app',
    measurementId: 'G-17CG2MWG21',
  );
}
